source 'https://rubygems.org'

group :development, :test do
  gem 'rspec', '3.4.0'
end

group :development do
  gem 'guard-rspec', '4.6.4'
  gem 'rb-fsevent', '0.9.7'
  gem 'rb-readline', '0.5.3'
end

group :test do
  gem 'simplecov', '0.11.2', require: false
end
