source 'https://rubygems.org'

group :development, :test do
  gem 'rspec', '2.14.1'
end

group :development do
  gem 'guard-rspec', '4.0.4'
  gem 'rb-fsevent', '0.9.3'
  gem 'rb-readline', '0.5.0'
end

group :test do
  gem 'simplecov', '0.8.2', :require => false
end
